// <auto-generated />
using System;
using FlightsTracking.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FlightsTracking.Persistence.Migrations
{
    [DbContext(typeof(TrackingFlightsDbContext))]
    partial class TrackingFlightsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FlightsTracking.Domain.Airport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Latitude")
                        .HasColumnType("float");

                    b.Property<double>("Longitude")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Airports");

                    b.HasData(
                        new
                        {
                            Id = new Guid("57d0c2a5-796b-49bf-8336-fcf749008971"),
                            Code = "CMN",
                            Latitude = 33.3699704,
                            Longitude = -7.5857231000000001,
                            Name = "Aéroport Mohamed V"
                        },
                        new
                        {
                            Id = new Guid("5f0adf77-6c6b-4b06-a61e-a9e302af7a46"),
                            Code = "ORY",
                            Latitude = 48.727699999999999,
                            Longitude = 2.3670800000000001,
                            Name = "Paris ORLY"
                        },
                        new
                        {
                            Id = new Guid("ea017e0e-e6eb-40fe-bca9-4eeecf47d58d"),
                            Code = "LHR",
                            Latitude = 51.4700256,
                            Longitude = -0.45648420000000001,
                            Name = "Londres Heathrow"
                        },
                        new
                        {
                            Id = new Guid("b0c36946-e543-4c3b-9daf-7e0724db4ffc"),
                            Code = "RAK",
                            Latitude = 32.926253600000003,
                            Longitude = 8.4107988999999996,
                            Name = "Marrakech"
                        },
                        new
                        {
                            Id = new Guid("fe6a6ade-af16-48e7-a323-432b4c4d2615"),
                            Code = "MAD",
                            Latitude = 40.493499999999997,
                            Longitude = -3.56629,
                            Name = "Madrid"
                        },
                        new
                        {
                            Id = new Guid("e4af1efb-4549-4cb1-bf02-21491e2f2261"),
                            Code = "CDG",
                            Latitude = 49.006999999999998,
                            Longitude = 2.55979,
                            Name = "Charles de Gaulle"
                        });
                });

            modelBuilder.Entity("FlightsTracking.Domain.Flight", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ArrivalAirport")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DepartureAirport")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("Distance")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Flights");
                });
#pragma warning restore 612, 618
        }
    }
}
